### ISSUE TITLE
Cannot install through PyPI

### ISSUE THREAD

**Issue by KatsuyamaE** [TadaoYamaoka/cshogi#39]
```
C:\Users\MY PC>pip install cshogi
Collecting cshogi
  Downloading cshogi-0.6.5.tar.gz (120 kB)
     ---------------------------------------- 120.7/120.7 kB 883.7 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      running egg_info
      writing cshogi.egg-info\PKG-INFO
      writing dependency_links to cshogi.egg-info\dependency_links.txt
      writing requirements to cshogi.egg-info\requires.txt
      writing top-level names to cshogi.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\MY PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\MY PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MY PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 33, in <module>
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 318, in run
          self.find_sources()
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
          mm.run()
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 548, in run
          self.add_defaults()
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\command\sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "C:\Users\MY PC\AppData\Local\Temp\pip-build-env-0h2b1lkj\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "<string>", line 14, in finalize_options
      AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by TadaoYamaoka** [comment]
Pythonのバージョンを教えてもらえないでしょうか。

**Comment by KatsuyamaE** [comment]
> Pythonのバージョンを教えてもらえないでしょうか。
3.12.0

**Comment by TadaoYamaoka** [comment]
v0.7.5でPython3.12に対応しました。
