### ISSUE TITLE
Problem when using pyinstaller

### ISSUE THREAD

**Issue by KatsuyamaE** [TadaoYamaoka/cshogi#50]
```
Traceback (most recent call last):
  File "ShogiBar1.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "cshogi\__init__.py", line 1, in <module>
  File "cshogi\\_cshogi.pyx", line 1, in init cshogi._cshogi
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
[14524] Failed to execute script 'ShogiBar1' due to unhandled exception!
```
When my script (using cshogi) is exported as a pyinstaller exe, it fails to load with this stack trace.

**Comment by KatsuyamaE** [comment]
Issue is still popping up now.
